require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.3
  TargetRailsVersion: 4.2

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/factories/*"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/factories/*"
    - 'config/routes.rb'
    - 'config/initializers/*'

Metrics/LineLength:
  Description: 'Limit lines to 130 characters.'
  Max: 130

Metrics/MethodLength:
  Max: 30

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MessageSpies:
  Enabled: false

StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading
